### DISCUSSION TITLE
Output the alignui tokens and tailwind config to a css file, making it work with `tailwindcss` v4

### DISCUSSION THREAD

**Discussion by remorses** [alignui/cli#3] [Ideas]
Tailwindcss v4 migrated the js config to a css file, meaning that each component library like alignui and shadcn can output the theme tokens to a css file instead of `tailwind.config.js` file, which means using alignui with a custom tailwind configuration is now much easier, here is the HR management app tailwind config converted to a css file following their [migration guide](https://tailwindcss.com/docs/v4-beta)

Changes to tailwind-merge:
```ts

export const twMergeConfig = {
  extend: {
    classGroups: {
      'font-size': [
        {
          text: [
            'title-h1',
            'title-h2',
            'title-h3',
            'title-h4',
            'title-h5',
            'title-h6',
            'label-xl',
            'label-lg',
            'label-md',
            'label-sm',
            'label-xs',
            'paragraph-xl',
            'paragraph-lg',
            'paragraph-md',
            'paragraph-sm',
            'paragraph-xs',
            'subheading-md',
            'subheading-sm',
            'subheading-xs',
            'subheading-2xs',
            'doc-label',
            'doc-paragraph',
          ],
        },
      ],
      shadow: [
        {
          shadow: [
            'regular-xs',
            'regular-sm',
            'regular-md',
            'button-primary-focus',
            'button-important-focus',
            'button-error-focus',
            'fancy-buttons-neutral',
            'fancy-buttons-primary',
            'fancy-buttons-error',
            'fancy-buttons-stroke',
            'toggle-switch',
            'switch-thumb',
            'tooltip',
          ],
        },
      ],
      rounded: [
        {
          rounded: ['10', '20'],
        },
      ],
    },
  },
};

const customTwMerge = extendTailwindMerge(twMergeConfig);

```

Tailwindcss config converted to css:

```css
@import 'tailwindcss';

/* Top-level options */
@source "./app/**/*.{js,ts,jsx,tsx,mdx}";
@source "./components/**/*.{js,ts,jsx,tsx,mdx}";
@source "./utils/**/*.{js,ts,jsx,tsx,mdx}";

@variant dark (&:where(.dark, .dark *));

@plugin "tailwindcss-animate";

/* Theme configuration */
@theme {
  /* Font sizes */
  --text-title-h1: 3.5rem;
  --text-title-h1--line-height: 4rem;
  --text-title-h1--letter-spacing: -0.01em;
  --text-title-h1--font-weight: 500;

  --text-title-h2: 3rem;
  --text-title-h2--line-height: 3.5rem;
  --text-title-h2--letter-spacing: -0.01em;
  --text-title-h2--font-weight: 500;

  --text-title-h3: 2.5rem;
  --text-title-h3--line-height: 3rem;
  --text-title-h3--letter-spacing: -0.01em;
  --text-title-h3--font-weight: 500;

  --text-title-h4: 2rem;
  --text-title-h4--line-height: 2.5rem;
  --text-title-h4--letter-spacing: -0.005em;
  --text-title-h4--font-weight: 500;

  --text-title-h5: 1.5rem;
  --text-title-h5--line-height: 2rem;
  --text-title-h5--letter-spacing: 0em;
  --text-title-h5--font-weight: 500;

  --text-title-h6: 1.25rem;
  --text-title-h6--line-height: 1.75rem;
  --text-title-h6--letter-spacing: 0em;
  --text-title-h6--font-weight: 500;

  --text-label-xl: 1.5rem;
  --text-label-xl--line-height: 2rem;
  --text-label-xl--letter-spacing: -0.015em;
  --text-label-xl--font-weight: 500;

  --text-label-lg: 1.125rem;
  --text-label-lg--line-height: 1.5rem;
  --text-label-lg--letter-spacing: -0.015em;
  --text-label-lg--font-weight: 500;

  --text-label-md: 1rem;
  --text-label-md--line-height: 1.5rem;
  --text-label-md--letter-spacing: -0.011em;
  --text-label-md--font-weight: 500;

  --text-label-sm: 0.875rem;
  --text-label-sm--line-height: 1.25rem;
  --text-label-sm--letter-spacing: -0.006em;
  --text-label-sm--font-weight: 500;

  --text-label-xs: 0.75rem;
  --text-label-xs--line-height: 1rem;
  --text-label-xs--letter-spacing: 0em;
  --text-label-xs--font-weight: 500;

  --text-paragraph-xl: 1.5rem;
  --text-paragraph-xl--line-height: 2rem;
  --text-paragraph-xl--letter-spacing: -0.015em;
  --text-paragraph-xl--font-weight: 400;

  --text-paragraph-lg: 1.125rem;
  --text-paragraph-lg--line-height: 1.5rem;
  --text-paragraph-lg--letter-spacing: -0.015em;
  --text-paragraph-lg--font-weight: 400;

  --text-paragraph-md: 1rem;
  --text-paragraph-md--line-height: 1.5rem;
  --text-paragraph-md--letter-spacing: -0.011em;
  --text-paragraph-md--font-weight: 400;

  --text-paragraph-sm: 0.875rem;
  --text-paragraph-sm--line-height: 1.25rem;
  --text-paragraph-sm--letter-spacing: -0.006em;
  --text-paragraph-sm--font-weight: 400;

  --text-paragraph-xs: 0.75rem;
  --text-paragraph-xs--line-height: 1rem;
  --text-paragraph-xs--letter-spacing: 0em;
  --text-paragraph-xs--font-weight: 400;

  --text-subheading-md: 1rem;
  --text-subheading-md--line-height: 1.5rem;
  --text-subheading-md--letter-spacing: 0.06em;
  --text-subheading-md--font-weight: 500;

  --text-subheading-sm: 0.875rem;
  --text-subheading-sm--line-height: 1.25rem;
  --text-subheading-sm--letter-spacing: 0.06em;
  --text-subheading-sm--font-weight: 500;

  --text-subheading-xs: 0.75rem;
  --text-subheading-xs--line-height: 1rem;
  --text-subheading-xs--letter-spacing: 0.04em;
  --text-subheading-xs--font-weight: 500;

  --text-subheading-2xs: 0.6875rem;
  --text-subheading-2xs--line-height: 0.75rem;
  --text-subheading-2xs--letter-spacing: 0.02em;
  --text-subheading-2xs--font-weight: 500;

  --text-doc-label: 1.125rem;
  --text-doc-label--line-height: 2rem;
  --text-doc-label--letter-spacing: -0.015em;
  --text-doc-label--font-weight: 500;

  --text-doc-paragraph: 1.125rem;
  --text-doc-paragraph--line-height: 2rem;
  --text-doc-paragraph--letter-spacing: -0.015em;
  --text-doc-paragraph--font-weight: 400;

  /* Shadows */
  --shadow-regular-xs: 0 1px 2px 0 #0a0d1408;
  --shadow-regular-sm: 0 2px 4px #1b1c1d0a;
  --shadow-regular-md: 0 16px 32px -12px #0e121b1a;
  --shadow-button-primary-focus: 0 0 0 2px var(--color-bg-white-0),
    0 0 0 4px var(--color-primary-alpha-10);
  --shadow-button-important-focus: 0 0 0 2px var(--color-bg-white-0),
    0 0 0 4px var(--color-neutral-alpha-16);
  --shadow-button-error-focus: 0 0 0 2px var(--color-bg-white-0),
    0 0 0 4px var(--color-red-alpha-10);
  --shadow-fancy-buttons-neutral: 0 1px 2px 0 #1b1c1d7a, 0 0 0 1px #242628;
  --shadow-fancy-buttons-primary: 0 1px 2px 0 #0e121b3d,
    0 0 0 1px var(--color-primary-base);
  --shadow-fancy-buttons-error: 0 1px 2px 0 #0e121b3d,
    0 0 0 1px var(--color-error-base);
  --shadow-fancy-buttons-stroke: 0 1px 3px 0 #0e121b1f,
    0 0 0 1px var(--color-stroke-soft-200);
  --shadow-toggle-switch: 0 6px 10px 0 #0e121b0f, 0 2px 4px 0 #0e121b08;
  --shadow-switch-thumb: 0 4px 8px 0 #1b1c1d0f, 0 2px 4px 0 #0e121b14;
  --shadow-tooltip: 0 12px 24px 0 #0e121b0f, 0 1px 2px 0 #0e121b08;

  /* Border radii */
  --radius-10: 0.625rem;
  --radius-20: 1.25rem;

  /* Colors */
  --color-neutral-0: hsl(var(--neutral-0));
  --color-neutral-50: hsl(var(--neutral-50));
  --color-neutral-100: hsl(var(--neutral-100));
  --color-neutral-200: hsl(var(--neutral-200));
  --color-neutral-300: hsl(var(--neutral-300));
  --color-neutral-400: hsl(var(--neutral-400));
  --color-neutral-500: hsl(var(--neutral-500));
  --color-neutral-600: hsl(var(--neutral-600));
  --color-neutral-700: hsl(var(--neutral-700));
  --color-neutral-800: hsl(var(--neutral-800));
  --color-neutral-900: hsl(var(--neutral-900));
  --color-neutral-alpha-10: hsl(var(--neutral-alpha-10));
  --color-neutral-alpha-16: hsl(var(--neutral-alpha-16));
  --color-neutral-alpha-24: hsl(var(--neutral-alpha-24));

  --color-blue-50: hsl(var(--blue-50));
  --color-blue-100: hsl(var(--blue-100));
  --color-blue-200: hsl(var(--blue-200));
  --color-blue-300: hsl(var(--blue-300));
  --color-blue-400: hsl(var(--blue-400));
  --color-blue-500: hsl(var(--blue-500));
  --color-blue-600: hsl(var(--blue-600));
  --color-blue-700: hsl(var(--blue-700));
  --color-blue-800: hsl(var(--blue-800));
  --color-blue-900: hsl(var(--blue-900));
  --color-blue-alpha-10: hsl(var(--blue-alpha-10));
  --color-blue-alpha-16: hsl(var(--blue-alpha-16));
  --color-blue-alpha-24: hsl(var(--blue-alpha-24));

  --color-orange-50: hsl(var(--orange-50));
  --color-orange-100: hsl(var(--orange-100));
  --color-orange-200: hsl(var(--orange-200));
  --color-orange-300: hsl(var(--orange-300));
  --color-orange-400: hsl(var(--orange-400));
  --color-orange-500: hsl(var(--orange-500));
  --color-orange-600: hsl(var(--orange-600));
  --color-orange-700: hsl(var(--orange-700));
  --color-orange-800: hsl(var(--orange-800));
  --color-orange-900: hsl(var(--orange-900));
  --color-orange-alpha-10: hsl(var(--orange-alpha-10));
  --color-orange-alpha-16: hsl(var(--orange-alpha-16));
  --color-orange-alpha-24: hsl(var(--orange-alpha-24));

  --color-red-50: hsl(var(--red-50));
  --color-red-100: hsl(var(--red-100));
  --color-red-200: hsl(var(--red-200));
  --color-red-300: hsl(var(--red-300));
  --color-red-400: hsl(var(--red-400));
  --color-red-500: hsl(var(--red-500));
  --color-red-600: hsl(var(--red-600));
  --color-red-700: hsl(var(--red-700));
  --color-red-800: hsl(var(--red-800));
  --color-red-900: hsl(var(--red-900));
  --color-red-alpha-10: hsl(var(--red-alpha-10));
  --color-red-alpha-16: hsl(var(--red-alpha-16));
  --color-red-alpha-24: hsl(var(--red-alpha-24));

  --color-green-50: hsl(var(--green-50));
  --color-green-100: hsl(var(--green-100));
  --color-green-200: hsl(var(--green-200));
  --color-green-300: hsl(var(--green-300));
  --color-green-400: hsl(var(--green-400));
  --color-green-500: hsl(var(--green-500));
  --color-green-600: hsl(var(--green-600));
  --color-green-700: hsl(var(--green-700));
  --color-green-800: hsl(var(--green-800));
  --color-green-900: hsl(var(--green-900));
  --color-green-alpha-10: hsl(var(--green-alpha-10));
  --color-green-alpha-16: hsl(var(--green-alpha-16));
  --color-green-alpha-24: hsl(var(--green-alpha-24));

  --color-primary-dark: hsl(var(--primary-dark));
  --color-primary-base: hsl(var(--primary-base));
  --color-primary-light: hsl(var(--primary-light));
  --color-primary-lighter: hsl(var(--primary-lighter));
  --color-primary-alpha-10: hsl(var(--primary-alpha-10));
  --color-primary-alpha-16: hsl(var(--primary-alpha-16));
  --color-primary-alpha-24: hsl(var(--primary-alpha-24));

  --color-error-dark: hsl(var(--error-dark));
  --color-error-base: hsl(var(--error-base));
  --color-error-light: hsl(var(--error-light));
  --color-error-lighter: hsl(var(--error-lighter));
  --color-error-alpha-10: hsl(var(--error-alpha-10));
  --color-error-alpha-16: hsl(var(--error-alpha-16));
  --color-error-alpha-24: hsl(var(--error-alpha-24));

  --color-warning-dark: hsl(var(--warning-dark));
  --color-warning-base: hsl(var(--warning-base));
  --color-warning-light: hsl(var(--warning-light));
  --color-warning-lighter: hsl(var(--warning-lighter));
  --color-warning-alpha-10: hsl(var(--warning-alpha-10));
  --color-warning-alpha-16: hsl(var(--warning-alpha-16));
  --color-warning-alpha-24: hsl(var(--warning-alpha-24));

  --color-success-dark: hsl(var(--success-dark));
  --color-success-base: hsl(var(--success-base));
  --color-success-light: hsl(var(--success-light));
  --color-success-lighter: hsl(var(--success-lighter));
  --color-success-alpha-10: hsl(var(--success-alpha-10));
  --color-success-alpha-16: hsl(var(--success-alpha-16));
  --color-success-alpha-24: hsl(var(--success-alpha-24));

  --color-feature-dark: hsl(var(--feature-dark));
  --color-feature-base: hsl(var(--feature-base));
  --color-feature-light: hsl(var(--feature-light));
  --color-feature-lighter: hsl(var(--feature-lighter));

  --color-verified-dark: hsl(var(--verified-dark));
  --color-verified-base: hsl(var(--verified-base));
  --color-verified-light: hsl(var(--verified-light));
  --color-verified-lighter: hsl(var(--verified-lighter));

  --color-highlighted-dark: hsl(var(--highlighted-dark));
  --color-highlighted-base: hsl(var(--highlighted-base));
  --color-highlighted-light: hsl(var(--highlighted-light));
  --color-highlighted-lighter: hsl(var(--highlighted-lighter));

  --color-stable-dark: hsl(var(--stable-dark));
  --color-stable-base: hsl(var(--stable-base));
  --color-stable-light: hsl(var(--stable-light));
  --color-stable-lighter: hsl(var(--stable-lighter));

  --color-social-apple: hsl(var(--social-apple));
  --color-social-twitter: hsl(var(--social-twitter));
  --color-social-github: hsl(var(--social-github));
  --color-social-notion: hsl(var(--social-notion));
  --color-social-tidal: hsl(var(--social-tidal));
  --color-social-amazon: hsl(var(--social-amazon));
  --color-social-zendesk: hsl(var(--social-zendesk));

  --color-overlay: hsl(var(--overlay));

  --color-illustration-weak-50: hsl(var(--illustration-weak-50));
  --color-illustration-weak-100: hsl(var(--illustration-weak-100));
  --color-illustration-weak-200: hsl(var(--illustration-weak-200));
  --color-illustration-weak-300: hsl(var(--illustration-weak-300));
  --color-illustration-weak-400: hsl(var(--illustration-weak-400));

  --color-illustration-sub-100: hsl(var(--illustration-sub-100));
  --color-illustration-sub-200: hsl(var(--illustration-sub-200));
  --color-illustration-sub-300: hsl(var(--illustration-sub-300));
  --color-illustration-sub-400: hsl(var(--illustration-sub-400));
  --color-illustration-sub-500: hsl(var(--illustration-sub-500));

  --color-illustration-soft-100: hsl(var(--illustration-soft-100));
  --color-illustration-soft-200: hsl(var(--illustration-soft-200));
  --color-illustration-soft-300: hsl(var(--illustration-soft-300));
  --color-illustration-soft-400: hsl(var(--illustration-soft-400));
  --color-illustration-soft-500: hsl(var(--illustration-soft-500));

  --color-illustration-white-0: hsl(var(--illustration-white-0));
  --color-illustration-white-100: hsl(var(--illustration-white-100));
  --color-illustration-white-200: hsl(var(--illustration-white-200));
  --color-illustration-white-300: hsl(var(--illustration-white-300));
  --color-illustration-white-400: hsl(var(--illustration-white-400));
  --color-illustration-strong-100: hsl(var(--illustration-strong-100));
  --color-illustration-strong-200: hsl(var(--illustration-strong-200));
  --color-illustration-strong-300: hsl(var(--illustration-strong-300));
  --color-illustration-strong-400: hsl(var(--illustration-strong-400));
  --color-illustration-strong-500: hsl(var(--illustration-strong-500));

  --color-illustration-main-100: hsl(var(--illustration-main-100));
  --color-illustration-main-200: hsl(var(--illustration-main-200));
  --color-illustration-main-300: hsl(var(--illustration-main-300));
  --color-illustration-main-400: hsl(var(--illustration-main-400));
  --color-illustration-main-500: hsl(var(--illustration-main-500));

  --color-primary-base: hsl(var(--primary-base));
  --color-primary-alpha-10: hsl(var(--primary-alpha-10));

  --color-static-black: hsl(var(--static-black));
  --color-static-white: hsl(var(--static-white));

  --color-bg-strong-950: hsl(var(--bg-strong-950));
  --color-bg-surface-800: hsl(var(--bg-surface-800));
  --color-bg-sub-300: hsl(var(--bg-sub-300));
  --color-bg-soft-200: hsl(var(--bg-soft-200));
  --color-bg-weak-50: hsl(var(--bg-weak-50));
  --color-bg-white-0: hsl(var(--bg-white-0));

  --color-text-strong-950: hsl(var(--text-strong-950));
  --color-text-sub-600: hsl(var(--text-sub-600));
  --color-text-soft-400: hsl(var(--text-soft-400));
  --color-text-disabled-300: hsl(var(--text-disabled-300));
  --color-text-white-0: hsl(var(--text-white-0));

  --color-stroke-strong-950: hsl(var(--stroke-strong-950));
  --color-stroke-sub-300: hsl(var(--stroke-sub-300));
  --color-stroke-soft-200: hsl(var(--stroke-soft-200));
  --color-stroke-white-0: hsl(var(--stroke-white-0));

  --color-faded-dark: hsl(var(--faded-dark));
  --color-faded-base: hsl(var(--faded-base));
  --color-faded-light: hsl(var(--faded-light));
  --color-faded-lighter: hsl(var(--faded-lighter));

  --color-information-dark: hsl(var(--information-dark));
  --color-information-base: hsl(var(--information-base));
  --color-information-light: hsl(var(--information-light));
  --color-information-lighter: hsl(var(--information-lighter));

  /* Animations */
  --animation-accordion-down: accordion-down 0.2s ease-out;
  --animation-accordion-up: accordion-up 0.2s ease-out;
  --animation-event-item-show: event-item-show 0.5s
    cubic-bezier(0.6, 1, 0.75, 0.9) forwards;

  /* Keyframes */
  @keyframes accordion-down {
    from {
      height: 0;
      opacity: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
      opacity: 1;
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
      opacity: 1;
    }
    to {
      height: 0;
      opacity: 0;
    }
  }

  @keyframes event-item-show {
    to {
      opacity: 1;
      transform: translate3d(0, 0, 0);
    }
  }
}

```
